### ISSUE TITLE
How do I use Release 3?

### ISSUE THREAD

**Issue by TV4Fun** [ksherlock/host-fst#5]
Sorry if this is an obvious question. I have downloaded release 3 and am trying to figure out how to install it. The installation instructions say to install the `host.fst` and `host.driver` in your `*:System:` folder, but there is no `host.fst` or `host.driver` in the release 3 disk image. Am I supposed to use the files from a previous release, or is there a different install process for release 3?

**Comment by ksherlock** [comment]
Ah, you're the release 3 disk image is just for ProDOS 8 (abusing the appleshare support).  Use the release 2 disk images for  GS/OS.  I will add them to the release 3 since GitHub hides them.

**Comment by TV4Fun** [comment]
Thanks very much! 😃
